name: Test

on:
  push:
    branches:
      - main
    tags: ["*"]
  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        version:
          - "1"
        os:
          - ubuntu-latest
          - macos-15
        # This logic ensures x64 for Linux and arm64 for Apple Silicon
        include:
          - os: ubuntu-latest
            arch: x64
          - os: macos-15
            arch: arm64
    
    uses: ./.github/workflows/ReusableTest.yml
    with:
      os: ${{ matrix.os }}
      version: ${{ matrix.version }}
      arch: ${{ matrix.arch }}
      allow_failure: ${{ matrix.allow_failure }}
      run_codecov: ${{ matrix.version == '1' && matrix.os == 'ubuntu-latest' }}
    secrets:
      codecov_token: ${{ secrets.CODECOV_TOKEN }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - "1"
          - "1"
        os:
          - ubuntu-latest

        arch:
          - x64
        allow_failure: [false]
